services:
  web:
    build:
      context: ./app
    container_name: fastapi-app-data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/enterprise?sslmode=disable
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: postgres-db-data
    restart: always
    environment:
      POSTGRES-USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: enterprise
    ports:
      - "5432:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


