services:
  web:
    build:
      context: ./app
    container_name: fastapi-app-data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://user:pass@db:27017/enterprise?authSource=admin
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: mongo:latest  # Usando imagem do MongoDB
    container_name: mongo-db-data
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=enterprise
    ports:
      - "27017:27017"  # Porta padrão do MongoDB
    volumes:  
      - mongo_data:/data/db  # Volumes para persistência de dados

volumes:
  mongo_data:
